//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiBand5WatchFaces.Forms {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NumberFormEdit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumberFormEdit() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiBand5WatchFaces.Forms.NumberFormEdit", typeof(NumberFormEdit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TopLeft.
        /// </summary>
        internal static string AligmentComboBox_Items {
            get {
                return ResourceManager.GetString("AligmentComboBox.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top.
        /// </summary>
        internal static string AligmentComboBox_Items1 {
            get {
                return ResourceManager.GetString("AligmentComboBox.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TopRight.
        /// </summary>
        internal static string AligmentComboBox_Items2 {
            get {
                return ResourceManager.GetString("AligmentComboBox.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left.
        /// </summary>
        internal static string AligmentComboBox_Items3 {
            get {
                return ResourceManager.GetString("AligmentComboBox.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Center.
        /// </summary>
        internal static string AligmentComboBox_Items4 {
            get {
                return ResourceManager.GetString("AligmentComboBox.Items4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right.
        /// </summary>
        internal static string AligmentComboBox_Items5 {
            get {
                return ResourceManager.GetString("AligmentComboBox.Items5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BottomLeft.
        /// </summary>
        internal static string AligmentComboBox_Items6 {
            get {
                return ResourceManager.GetString("AligmentComboBox.Items6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom.
        /// </summary>
        internal static string AligmentComboBox_Items7 {
            get {
                return ResourceManager.GetString("AligmentComboBox.Items7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BottomRight.
        /// </summary>
        internal static string AligmentComboBox_Items8 {
            get {
                return ResourceManager.GetString("AligmentComboBox.Items8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=88,Y=23}.
        /// </summary>
        internal static System.Drawing.Point AligmentComboBox_Location {
            get {
                object obj = ResourceManager.GetObject("AligmentComboBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=106, Height=26}.
        /// </summary>
        internal static System.Drawing.Size AligmentComboBox_Size {
            get {
                object obj = ResourceManager.GetObject("AligmentComboBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 0.
        /// </summary>
        internal static int AligmentComboBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("AligmentComboBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft Sans Serif, Size=11,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font deleteButton_Font {
            get {
                object obj = ResourceManager.GetObject("deleteButton.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=12,Y=595}.
        /// </summary>
        internal static System.Drawing.Point deleteButton_Location {
            get {
                object obj = ResourceManager.GetObject("deleteButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=204, Height=32}.
        /// </summary>
        internal static System.Drawing.Size deleteButton_Size {
            get {
                object obj = ResourceManager.GetObject("deleteButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 2.
        /// </summary>
        internal static int deleteButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("deleteButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string deleteButton_Text {
            get {
                return ResourceManager.GetString("deleteButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=26}.
        /// </summary>
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=76, Height=18}.
        /// </summary>
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 1.
        /// </summary>
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alignment:.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool label2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=57}.
        /// </summary>
        internal static System.Drawing.Point label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=79, Height=18}.
        /// </summary>
        internal static System.Drawing.Size label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 4.
        /// </summary>
        internal static int label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spacing X:.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool label3_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label3.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=87}.
        /// </summary>
        internal static System.Drawing.Point label3_Location {
            get {
                object obj = ResourceManager.GetObject("label3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=78, Height=18}.
        /// </summary>
        internal static System.Drawing.Size label3_Size {
            get {
                object obj = ResourceManager.GetObject("label3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 5.
        /// </summary>
        internal static int label3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spacing Y:.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Bottom, Left.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles label4_Anchor {
            get {
                object obj = ResourceManager.GetObject("label4.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool label4_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label4.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=72,Y=173}.
        /// </summary>
        internal static System.Drawing.Point label4_Location {
            get {
                object obj = ResourceManager.GetObject("label4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=60, Height=18}.
        /// </summary>
        internal static System.Drawing.Size label4_Size {
            get {
                object obj = ResourceManager.GetObject("label4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 7.
        /// </summary>
        internal static int label4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preview.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool label5_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label5.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=117}.
        /// </summary>
        internal static System.Drawing.Point label5_Location {
            get {
                object obj = ResourceManager.GetObject("label5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=41, Height=18}.
        /// </summary>
        internal static System.Drawing.Size label5_Size {
            get {
                object obj = ResourceManager.GetObject("label5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 9.
        /// </summary>
        internal static int label5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size:.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool label6_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label6.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=147}.
        /// </summary>
        internal static System.Drawing.Point label6_Location {
            get {
                object obj = ResourceManager.GetObject("label6.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=66, Height=18}.
        /// </summary>
        internal static System.Drawing.Size label6_Size {
            get {
                object obj = ResourceManager.GetObject("label6.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 12.
        /// </summary>
        internal static int label6_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label6.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position:.
        /// </summary>
        internal static string label6_Text {
            get {
                return ResourceManager.GetString("label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=88,Y=145}.
        /// </summary>
        internal static System.Drawing.Point posXNum_Location {
            get {
                object obj = ResourceManager.GetObject("posXNum.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=24}.
        /// </summary>
        internal static System.Drawing.Size posXNum_Size {
            get {
                object obj = ResourceManager.GetObject("posXNum.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 13.
        /// </summary>
        internal static int posXNum_TabIndex {
            get {
                object obj = ResourceManager.GetObject("posXNum.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=145,Y=145}.
        /// </summary>
        internal static System.Drawing.Point posYNum_Location {
            get {
                object obj = ResourceManager.GetObject("posYNum.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=24}.
        /// </summary>
        internal static System.Drawing.Size posYNum_Size {
            get {
                object obj = ResourceManager.GetObject("posYNum.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 14.
        /// </summary>
        internal static int posYNum_TabIndex {
            get {
                object obj = ResourceManager.GetObject("posYNum.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Bottom, Left.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles previewImage_Anchor {
            get {
                object obj = ResourceManager.GetObject("previewImage.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=39,Y=194}.
        /// </summary>
        internal static System.Drawing.Point previewImage_Location {
            get {
                object obj = ResourceManager.GetObject("previewImage.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=126, Height=294}.
        /// </summary>
        internal static System.Drawing.Size previewImage_Size {
            get {
                object obj = ResourceManager.GetObject("previewImage.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 6.
        /// </summary>
        internal static int previewImage_TabIndex {
            get {
                object obj = ResourceManager.GetObject("previewImage.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного False.
        /// </summary>
        internal static bool PropertiesGroupBox_Enabled {
            get {
                object obj = ResourceManager.GetObject("PropertiesGroupBox.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft Sans Serif, Size=11,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font PropertiesGroupBox_Font {
            get {
                object obj = ResourceManager.GetObject("PropertiesGroupBox.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=12,Y=50}.
        /// </summary>
        internal static System.Drawing.Point PropertiesGroupBox_Location {
            get {
                object obj = ResourceManager.GetObject("PropertiesGroupBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=204, Height=535}.
        /// </summary>
        internal static System.Drawing.Size PropertiesGroupBox_Size {
            get {
                object obj = ResourceManager.GetObject("PropertiesGroupBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 1.
        /// </summary>
        internal static int PropertiesGroupBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("PropertiesGroupBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        internal static string PropertiesGroupBox_Text {
            get {
                return ResourceManager.GetString("PropertiesGroupBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Bottom, Left.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles saveBtn_Anchor {
            get {
                object obj = ResourceManager.GetObject("saveBtn.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=3,Y=494}.
        /// </summary>
        internal static System.Drawing.Point saveBtn_Location {
            get {
                object obj = ResourceManager.GetObject("saveBtn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=195, Height=33}.
        /// </summary>
        internal static System.Drawing.Size saveBtn_Size {
            get {
                object obj = ResourceManager.GetObject("saveBtn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 8.
        /// </summary>
        internal static int saveBtn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("saveBtn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string saveBtn_Text {
            get {
                return ResourceManager.GetString("saveBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft Sans Serif, Size=11,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font selectImages_Font {
            get {
                object obj = ResourceManager.GetObject("selectImages.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=12,Y=12}.
        /// </summary>
        internal static System.Drawing.Point selectImages_Location {
            get {
                object obj = ResourceManager.GetObject("selectImages.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=204, Height=32}.
        /// </summary>
        internal static System.Drawing.Size selectImages_Size {
            get {
                object obj = ResourceManager.GetObject("selectImages.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 0.
        /// </summary>
        internal static int selectImages_TabIndex {
            get {
                object obj = ResourceManager.GetObject("selectImages.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select images.
        /// </summary>
        internal static string selectImages_Text {
            get {
                return ResourceManager.GetString("selectImages.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=88,Y=115}.
        /// </summary>
        internal static System.Drawing.Point sizeXNum_Location {
            get {
                object obj = ResourceManager.GetObject("sizeXNum.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=24}.
        /// </summary>
        internal static System.Drawing.Size sizeXNum_Size {
            get {
                object obj = ResourceManager.GetObject("sizeXNum.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 10.
        /// </summary>
        internal static int sizeXNum_TabIndex {
            get {
                object obj = ResourceManager.GetObject("sizeXNum.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=145,Y=115}.
        /// </summary>
        internal static System.Drawing.Point sizeYNum_Location {
            get {
                object obj = ResourceManager.GetObject("sizeYNum.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=24}.
        /// </summary>
        internal static System.Drawing.Size sizeYNum_Size {
            get {
                object obj = ResourceManager.GetObject("sizeYNum.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 11.
        /// </summary>
        internal static int sizeYNum_TabIndex {
            get {
                object obj = ResourceManager.GetObject("sizeYNum.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=88,Y=55}.
        /// </summary>
        internal static System.Drawing.Point spacingXNum_Location {
            get {
                object obj = ResourceManager.GetObject("spacingXNum.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=24}.
        /// </summary>
        internal static System.Drawing.Size spacingXNum_Size {
            get {
                object obj = ResourceManager.GetObject("spacingXNum.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 2.
        /// </summary>
        internal static int spacingXNum_TabIndex {
            get {
                object obj = ResourceManager.GetObject("spacingXNum.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=88,Y=85}.
        /// </summary>
        internal static System.Drawing.Point spaсingYNum_Location {
            get {
                object obj = ResourceManager.GetObject("spaсingYNum.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=24}.
        /// </summary>
        internal static System.Drawing.Size spaсingYNum_Size {
            get {
                object obj = ResourceManager.GetObject("spaсingYNum.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 3.
        /// </summary>
        internal static int spaсingYNum_TabIndex {
            get {
                object obj = ResourceManager.GetObject("spaсingYNum.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
