//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiBand5WatchFaces {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiBand5WatchFaces.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=147, Height=22}.
        /// </summary>
        public static System.Drawing.Size aboutToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("aboutToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string aboutToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size activityToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("activityToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activity.
        /// </summary>
        public static string activityToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("activityToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddElement_Image {
            get {
                object obj = ResourceManager.GetObject("AddElement.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Color, аналогичного Color [Magenta].
        /// </summary>
        public static System.Drawing.Color AddElement_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("AddElement.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=88, Height=22}.
        /// </summary>
        public static System.Drawing.Size AddElement_Size {
            get {
                object obj = ResourceManager.GetObject("AddElement.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Element.
        /// </summary>
        public static string AddElement_Text {
            get {
                return ResourceManager.GetString("AddElement.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size alarmToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("alarmToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alarm.
        /// </summary>
        public static string alarmToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("alarmToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size analogDialFaceToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("analogDialFaceToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analog Dial Face.
        /// </summary>
        public static string analogDialFaceToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("analogDialFaceToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        public static bool AnimateCheckBox_AutoSize {
            get {
                object obj = ResourceManager.GetObject("AnimateCheckBox.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного BottomCenter.
        /// </summary>
        public static System.Drawing.ContentAlignment AnimateCheckBox_CheckAlign {
            get {
                object obj = ResourceManager.GetObject("AnimateCheckBox.CheckAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode AnimateCheckBox_ImeMode {
            get {
                object obj = ResourceManager.GetObject("AnimateCheckBox.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=375,Y=481}.
        /// </summary>
        public static System.Drawing.Point AnimateCheckBox_Location {
            get {
                object obj = ResourceManager.GetObject("AnimateCheckBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=31}.
        /// </summary>
        public static System.Drawing.Size AnimateCheckBox_Size {
            get {
                object obj = ResourceManager.GetObject("AnimateCheckBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 11.
        /// </summary>
        public static int AnimateCheckBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("AnimateCheckBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Animate.
        /// </summary>
        public static string AnimateCheckBox_Text {
            get {
                return ResourceManager.GetString("AnimateCheckBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=652,Y=17}.
        /// </summary>
        public static System.Drawing.Point AnimateTimer_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("AnimateTimer.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size animationToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("animationToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Animation.
        /// </summary>
        public static string animationToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("animationToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size backgroundToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("backgroundToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background.
        /// </summary>
        public static string backgroundToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("backgroundToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size batteryToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("batteryToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Battery.
        /// </summary>
        public static string batteryToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("batteryToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size caloriesProgressToolStripMenuItem1_Size {
            get {
                object obj = ResourceManager.GetObject("caloriesProgressToolStripMenuItem1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calories Progress.
        /// </summary>
        public static string caloriesProgressToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("caloriesProgressToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=147, Height=22}.
        /// </summary>
        public static System.Drawing.Size changeLogToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("changeLogToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change log.
        /// </summary>
        public static string changeLogToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("changeLogToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=147, Height=22}.
        /// </summary>
        public static System.Drawing.Size checkUpdateToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("checkUpdateToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check update.
        /// </summary>
        public static string checkUpdateToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("checkUpdateToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CloseProjectButton_Image {
            get {
                object obj = ResourceManager.GetObject("CloseProjectButton.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Color, аналогичного Color [Magenta].
        /// </summary>
        public static System.Drawing.Color CloseProjectButton_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("CloseProjectButton.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=97, Height=22}.
        /// </summary>
        public static System.Drawing.Size CloseProjectButton_Size {
            get {
                object obj = ResourceManager.GetObject("CloseProjectButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close watchface.
        /// </summary>
        public static string CloseProjectButton_Text {
            get {
                return ResourceManager.GetString("CloseProjectButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode convertGIFToPNGButton_ImeMode {
            get {
                object obj = ResourceManager.GetObject("convertGIFToPNGButton.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=48}.
        /// </summary>
        public static System.Drawing.Point convertGIFToPNGButton_Location {
            get {
                object obj = ResourceManager.GetObject("convertGIFToPNGButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=162, Height=23}.
        /// </summary>
        public static System.Drawing.Size convertGIFToPNGButton_Size {
            get {
                object obj = ResourceManager.GetObject("convertGIFToPNGButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 1.
        /// </summary>
        public static int convertGIFToPNGButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("convertGIFToPNGButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert GIF to Png.
        /// </summary>
        public static string convertGIFToPNGButton_Text {
            get {
                return ResourceManager.GetString("convertGIFToPNGButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size dateToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("dateToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string dateToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("dateToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=780,Y=17}.
        /// </summary>
        public static System.Drawing.Point DeleteTrash_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("DeleteTrash.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=117, Height=22}.
        /// </summary>
        public static System.Drawing.Size editToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("editToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string editToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("editToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=180, Height=22}.
        /// </summary>
        public static System.Drawing.Size englishToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("englishToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string englishToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("englishToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=147, Height=22}.
        /// </summary>
        public static System.Drawing.Size findBugToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("findBugToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find bug?.
        /// </summary>
        public static string findBugToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("findBugToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Top, Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles groupBox1_Anchor {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=613,Y=28}.
        /// </summary>
        public static System.Drawing.Point groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=174, Height=546}.
        /// </summary>
        public static System.Drawing.Size groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 6.
        /// </summary>
        public static int groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Controls.
        /// </summary>
        public static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size heartProgressToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("heartProgressToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heart Progress.
        /// </summary>
        public static string heartProgressToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("heartProgressToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        public static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=7,Y=136}.
        /// </summary>
        public static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=58, Height=13}.
        /// </summary>
        public static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 6.
        /// </summary>
        public static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        public static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=118, Height=48}.
        /// </summary>
        public static System.Drawing.Size listMenuStrip_Size {
            get {
                object obj = ResourceManager.GetObject("listMenuStrip.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=122,Y=17}.
        /// </summary>
        public static System.Drawing.Point listMenuStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("listMenuStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Top, Bottom, Left.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles listViewElements_Anchor {
            get {
                object obj = ResourceManager.GetObject("listViewElements.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft Sans Serif, Size=11,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font listViewElements_Font {
            get {
                object obj = ResourceManager.GetObject("listViewElements.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=12,Y=28}.
        /// </summary>
        public static System.Drawing.Point listViewElements_Location {
            get {
                object obj = ResourceManager.GetObject("listViewElements.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=174, Height=546}.
        /// </summary>
        public static System.Drawing.Size listViewElements_Size {
            get {
                object obj = ResourceManager.GetObject("listViewElements.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 9.
        /// </summary>
        public static int listViewElements_TabIndex {
            get {
                object obj = ResourceManager.GetObject("listViewElements.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=127, Height=22}.
        /// </summary>
        public static System.Drawing.Size miBand5ToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("miBand5ToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mi Band 5.
        /// </summary>
        public static string miBand5ToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("miBand5ToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=127, Height=22}.
        /// </summary>
        public static System.Drawing.Size miBand6ToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("miBand6ToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mi Band 6.
        /// </summary>
        public static string miBand6ToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("miBand6ToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode openDirectoryWatchface_ImeMode {
            get {
                object obj = ResourceManager.GetObject("openDirectoryWatchface.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=77}.
        /// </summary>
        public static System.Drawing.Point openDirectoryWatchface_Location {
            get {
                object obj = ResourceManager.GetObject("openDirectoryWatchface.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=162, Height=23}.
        /// </summary>
        public static System.Drawing.Size openDirectoryWatchface_Size {
            get {
                object obj = ResourceManager.GetObject("openDirectoryWatchface.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 3.
        /// </summary>
        public static int openDirectoryWatchface_TabIndex {
            get {
                object obj = ResourceManager.GetObject("openDirectoryWatchface.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open directory.
        /// </summary>
        public static string openDirectoryWatchface_Text {
            get {
                return ResourceManager.GetString("openDirectoryWatchface.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.Keys, аналогичного O, Control.
        /// </summary>
        public static System.Windows.Forms.Keys openFileButton_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("openFileButton.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=184, Height=22}.
        /// </summary>
        public static System.Drawing.Size openFileButton_Size {
            get {
                object obj = ResourceManager.GetObject("openFileButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string openFileButton_Text {
            get {
                return ResourceManager.GetString("openFileButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OpenFormImages_Image {
            get {
                object obj = ResourceManager.GetObject("OpenFormImages.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Color, аналогичного Color [Magenta].
        /// </summary>
        public static System.Drawing.Color OpenFormImages_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("OpenFormImages.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=22}.
        /// </summary>
        public static System.Drawing.Size OpenFormImages_Size {
            get {
                object obj = ResourceManager.GetObject("OpenFormImages.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Images.
        /// </summary>
        public static string OpenFormImages_Text {
            get {
                return ResourceManager.GetString("OpenFormImages.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OpenJsonButton_Image {
            get {
                object obj = ResourceManager.GetObject("OpenJsonButton.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Color, аналогичного Color [Magenta].
        /// </summary>
        public static System.Drawing.Color OpenJsonButton_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("OpenJsonButton.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=105, Height=22}.
        /// </summary>
        public static System.Drawing.Size OpenJsonButton_Size {
            get {
                object obj = ResourceManager.GetObject("OpenJsonButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open JSON Editor.
        /// </summary>
        public static string OpenJsonButton_Text {
            get {
                return ResourceManager.GetString("OpenJsonButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        public static bool radioButton1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("radioButton1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=152}.
        /// </summary>
        public static System.Drawing.Point radioButton1_Location {
            get {
                object obj = ResourceManager.GetObject("radioButton1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=55, Height=17}.
        /// </summary>
        public static System.Drawing.Size radioButton1_Size {
            get {
                object obj = ResourceManager.GetObject("radioButton1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 5.
        /// </summary>
        public static int radioButton1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("radioButton1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Global.
        /// </summary>
        public static string radioButton1_Text {
            get {
                return ResourceManager.GetString("radioButton1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        public static bool radioButton2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("radioButton2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode radioButton2_ImeMode {
            get {
                object obj = ResourceManager.GetObject("radioButton2.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=175}.
        /// </summary>
        public static System.Drawing.Point radioButton2_Location {
            get {
                object obj = ResourceManager.GetObject("radioButton2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=96, Height=17}.
        /// </summary>
        public static System.Drawing.Size radioButton2_Size {
            get {
                object obj = ResourceManager.GetObject("radioButton2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 7.
        /// </summary>
        public static int radioButton2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("radioButton2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simple chinese.
        /// </summary>
        public static string radioButton2_Text {
            get {
                return ResourceManager.GetString("radioButton2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        public static bool radioButton3_AutoSize {
            get {
                object obj = ResourceManager.GetObject("radioButton3.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode radioButton3_ImeMode {
            get {
                object obj = ResourceManager.GetObject("radioButton3.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=198}.
        /// </summary>
        public static System.Drawing.Point radioButton3_Location {
            get {
                object obj = ResourceManager.GetObject("radioButton3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=63, Height=17}.
        /// </summary>
        public static System.Drawing.Size radioButton3_Size {
            get {
                object obj = ResourceManager.GetObject("radioButton3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 8.
        /// </summary>
        public static int radioButton3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("radioButton3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chinese.
        /// </summary>
        public static string radioButton3_Text {
            get {
                return ResourceManager.GetString("radioButton3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=117, Height=22}.
        /// </summary>
        public static System.Drawing.Size removeToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("removeToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string removeToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("removeToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Top.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles RenderButton_Anchor {
            get {
                object obj = ResourceManager.GetObject("RenderButton.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode RenderButton_ImeMode {
            get {
                object obj = ResourceManager.GetObject("RenderButton.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=362,Y=452}.
        /// </summary>
        public static System.Drawing.Point RenderButton_Location {
            get {
                object obj = ResourceManager.GetObject("RenderButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size RenderButton_Size {
            get {
                object obj = ResourceManager.GetObject("RenderButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 8.
        /// </summary>
        public static int RenderButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("RenderButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rerender.
        /// </summary>
        public static string RenderButton_Text {
            get {
                return ResourceManager.GetString("RenderButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=180, Height=22}.
        /// </summary>
        public static System.Drawing.Size russianToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("russianToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        public static string russianToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("russianToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.Keys, аналогичного S, Shift, Control.
        /// </summary>
        public static System.Windows.Forms.Keys saveAsToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("saveAsToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=184, Height=22}.
        /// </summary>
        public static System.Drawing.Size saveAsToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("saveAsToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as.
        /// </summary>
        public static string saveAsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveAsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=184, Height=22}.
        /// </summary>
        public static System.Drawing.Size saveBinToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("saveBinToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save bin.
        /// </summary>
        public static string saveBinToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveBinToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=0, Height=17}.
        /// </summary>
        public static System.Drawing.Size SaveFileStatus_Size {
            get {
                object obj = ResourceManager.GetObject("SaveFileStatus.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.Keys, аналогичного S, Control.
        /// </summary>
        public static System.Windows.Forms.Keys saveToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("saveToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=184, Height=22}.
        /// </summary>
        public static System.Drawing.Size saveToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("saveToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string saveToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode SettingsEXE_ImeMode {
            get {
                object obj = ResourceManager.GetObject("SettingsEXE.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=106}.
        /// </summary>
        public static System.Drawing.Point SettingsEXE_Location {
            get {
                object obj = ResourceManager.GetObject("SettingsEXE.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=162, Height=23}.
        /// </summary>
        public static System.Drawing.Size SettingsEXE_Size {
            get {
                object obj = ResourceManager.GetObject("SettingsEXE.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 4.
        /// </summary>
        public static int SettingsEXE_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SettingsEXE.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open settings.
        /// </summary>
        public static string SettingsEXE_Text {
            get {
                return ResourceManager.GetString("SettingsEXE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode SetWatchfaceState_ImeMode {
            get {
                object obj = ResourceManager.GetObject("SetWatchfaceState.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=19}.
        /// </summary>
        public static System.Drawing.Point SetWatchfaceState_Location {
            get {
                object obj = ResourceManager.GetObject("SetWatchfaceState.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=162, Height=23}.
        /// </summary>
        public static System.Drawing.Size SetWatchfaceState_Size {
            get {
                object obj = ResourceManager.GetObject("SetWatchfaceState.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 0.
        /// </summary>
        public static int SetWatchfaceState_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SetWatchfaceState.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set watchface state.
        /// </summary>
        public static string SetWatchfaceState_Text {
            get {
                return ResourceManager.GetString("SetWatchfaceState.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=180, Height=22}.
        /// </summary>
        public static System.Drawing.Size simpleToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("simpleToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simplified Chinese.
        /// </summary>
        public static string simpleToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("simpleToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size statusSimplifiedToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("statusSimplifiedToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status Simplified.
        /// </summary>
        public static string statusSimplifiedToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("statusSimplifiedToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=0,Y=577}.
        /// </summary>
        public static System.Drawing.Point statusStrip1_Location {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=799, Height=22}.
        /// </summary>
        public static System.Drawing.Size statusStrip1_Size {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 10.
        /// </summary>
        public static int statusStrip1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на statusStrip1.
        /// </summary>
        public static string statusStrip1_Text {
            get {
                return ResourceManager.GetString("statusStrip1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=377,Y=17}.
        /// </summary>
        public static System.Drawing.Point statusStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size statusToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("statusToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string statusToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("statusToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size stepsProgressToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("stepsProgressToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steps Progress.
        /// </summary>
        public static string stepsProgressToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("stepsProgressToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft Sans Serif, Size=9,75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font SupportAuthorButton_Font {
            get {
                object obj = ResourceManager.GetObject("SupportAuthorButton.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode SupportAuthorButton_ImeMode {
            get {
                object obj = ResourceManager.GetObject("SupportAuthorButton.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=6,Y=508}.
        /// </summary>
        public static System.Drawing.Point SupportAuthorButton_Location {
            get {
                object obj = ResourceManager.GetObject("SupportAuthorButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=162, Height=32}.
        /// </summary>
        public static System.Drawing.Size SupportAuthorButton_Size {
            get {
                object obj = ResourceManager.GetObject("SupportAuthorButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 2.
        /// </summary>
        public static int SupportAuthorButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SupportAuthorButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support author.
        /// </summary>
        public static string SupportAuthorButton_Text {
            get {
                return ResourceManager.GetString("SupportAuthorButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=147, Height=22}.
        /// </summary>
        public static System.Drawing.Size supportMeButton_Size {
            get {
                object obj = ResourceManager.GetObject("supportMeButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support me.
        /// </summary>
        public static string supportMeButton_Text {
            get {
                return ResourceManager.GetString("supportMeButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=493,Y=17}.
        /// </summary>
        public static System.Drawing.Point timerWatchFaceEXE_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timerWatchFaceEXE.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size timeToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("timeToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string timeToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("timeToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point toolStrip1_Location {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=799, Height=25}.
        /// </summary>
        public static System.Drawing.Size toolStrip1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 3.
        /// </summary>
        public static int toolStrip1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на toolStrip1.
        /// </summary>
        public static string toolStrip1_Text {
            get {
                return ResourceManager.GetString("toolStrip1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point toolStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripDropDownButton1_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton1.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Color, аналогичного Color [Magenta].
        /// </summary>
        public static System.Drawing.Color toolStripDropDownButton1_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton1.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=38, Height=22}.
        /// </summary>
        public static System.Drawing.Size toolStripDropDownButton1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string toolStripDropDownButton1_Text {
            get {
                return ResourceManager.GetString("toolStripDropDownButton1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripDropDownButton2_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Color, аналогичного Color [Magenta].
        /// </summary>
        public static System.Drawing.Color toolStripDropDownButton2_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton2.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=60, Height=22}.
        /// </summary>
        public static System.Drawing.Size toolStripDropDownButton2_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string toolStripDropDownButton2_Text {
            get {
                return ResourceManager.GetString("toolStripDropDownButton2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripDropDownButton3_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton3.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Color, аналогичного Color [Magenta].
        /// </summary>
        public static System.Drawing.Color toolStripDropDownButton3_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton3.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=72, Height=22}.
        /// </summary>
        public static System.Drawing.Size toolStripDropDownButton3_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string toolStripDropDownButton3_Text {
            get {
                return ResourceManager.GetString("toolStripDropDownButton3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripDropDownButton4_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton4.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Color, аналогичного Color [Magenta].
        /// </summary>
        public static System.Drawing.Color toolStripDropDownButton4_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton4.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=89, Height=22}.
        /// </summary>
        public static System.Drawing.Size toolStripDropDownButton4_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model watch.
        /// </summary>
        public static string toolStripDropDownButton4_Text {
            get {
                return ResourceManager.GetString("toolStripDropDownButton4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=6, Height=25}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=144, Height=6}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator2_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=6, Height=25}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator3_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=236,Y=27}.
        /// </summary>
        public static System.Drawing.Point WatchFaceEXE_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("WatchFaceEXE.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного None.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles watchfacePreviewImage_Anchor {
            get {
                object obj = ResourceManager.GetObject("watchfacePreviewImage.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode watchfacePreviewImage_ImeMode {
            get {
                object obj = ResourceManager.GetObject("watchfacePreviewImage.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=336,Y=152}.
        /// </summary>
        public static System.Drawing.Point watchfacePreviewImage_Location {
            get {
                object obj = ResourceManager.GetObject("watchfacePreviewImage.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=126, Height=294}.
        /// </summary>
        public static System.Drawing.Size watchfacePreviewImage_Size {
            get {
                object obj = ResourceManager.GetObject("watchfacePreviewImage.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 7.
        /// </summary>
        public static int watchfacePreviewImage_TabIndex {
            get {
                object obj = ResourceManager.GetObject("watchfacePreviewImage.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size weatherToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("weatherToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weather.
        /// </summary>
        public static string weatherToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("weatherToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=164, Height=22}.
        /// </summary>
        public static System.Drawing.Size weekDaysIconsToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("weekDaysIconsToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Week Days Icons.
        /// </summary>
        public static string weekDaysIconsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("weekDaysIconsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=147, Height=22}.
        /// </summary>
        public static System.Drawing.Size wkiProgramToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("wkiProgramToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wiki program.
        /// </summary>
        public static string wkiProgramToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("wkiProgramToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
